"""
Project scaffold generator for AgenticStarter
"""

import os
from pathlib import Path


def generate_project_scaffold(project_name: str, base_path: str = ".") -> Path:
    """
    Generate a project scaffold with standard Python project structure.

    Args:
        project_name: Name of the project to create
        base_path: Base directory where the project should be created

    Returns:
        Path to the created project directory

    Raises:
        FileExistsError: If the project directory already exists
    """
    # Create project directory
    project_path = Path(base_path) / project_name
    if project_path.exists():
        raise FileExistsError(f"Directory {project_path} already exists")

    project_path.mkdir(parents=True, exist_ok=False)

    # Create src package directory
    src_path = project_path / "src" / project_name.replace("-", "_")
    src_path.mkdir(parents=True, exist_ok=True)

    # Create tests directory
    tests_path = project_path / "tests"
    tests_path.mkdir(parents=True, exist_ok=True)

    # Create pyproject.toml
    pyproject_content = f"""[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "{project_name}"
version = "0.1.0"
description = "An agentic tool micro-SaaS"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["{project_name.replace("-", "_")}*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
"""
    (project_path / "pyproject.toml").write_text(pyproject_content)

    # Create src/__init__.py
    init_content = f'''"""
{project_name} - An agentic tool micro-SaaS
"""

__version__ = "0.1.0"
'''
    (src_path / "__init__.py").write_text(init_content)

    # Create tests/__init__.py
    (tests_path / "__init__.py").write_text("")

    # Create README.md
    readme_content = f"""# {project_name}

An agentic tool micro-SaaS generated by AgenticStarter.

## Installation

```bash
python -m venv venv
source venv/bin/activate
pip install -e .
```

## Development

```bash
pip install -e ".[dev]"
pytest
```

## Usage

TODO: Add usage instructions
"""
    (project_path / "README.md").write_text(readme_content)

    # Create .gitignore
    gitignore_content = """# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# Virtual environments
venv/
env/
ENV/

# IDE
.vscode/
.idea/
*.swp
*.swo
*~

# Testing
.pytest_cache/
.coverage
htmlcov/

# OS
.DS_Store
Thumbs.db
"""
    (project_path / ".gitignore").write_text(gitignore_content)

    return project_path
